import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar/NavBar";
import { SessionProvider } from "next-auth/react";
import SideBarWrapper from "@/components/sidebar/SideBarWrapper";
import { ToastContainer } from "react-toastify";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
        <ToastContainer />
        <SessionProvider>
          <div className="flex flex-row w-full h-full">
            <SideBarWrapper />
            <div className="flex flex-col flex-1 min-h-dvh">
              <NavBar />
              <div className="p-12 flex-1 flex flex-col">{children}</div>
            </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
